[package]
name = "platypus"
version = "0.1.6"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com>"]
description = "API layer on top of TMF620 to provide product composition"
repository = "https://github.com/rruckley/platypus"
keywords = ["tmf"]

[features]
core = []
composable = ["core"]
tmf620_v4 = []
tmf622_v4 = []
tmf632_v4 = []
tmf620_v5 = []
tmf622_v5 = []
tmf632_v5 = []
v4 = ["tmf620_v4","tmf622_v4","tmf632_v4"]
v5 = ["tmf620_v5","tmf622_v5","tmf632_v5"]
default = ["core","v4"]

[dependencies]
actix-web = { version = "4.5", features = ["rustls"]}
env_logger = "0.11"
log = "0.4.21"
serde = "1.0.197"
serde_json = "1.0.114"
surrealdb = {version = "1.3.1"}
tmflib = { git = "https://github.com/rruckley/tmflib.git"}


