[package]
name = "platypus"
version = "0.1.5"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com>"]
description = "API layer on top of TMF620 to provide product composition"
repository = "https://github.com/rruckley/platypus"
keywords = ["tmf"]

[features]
core = []
composable = ["core"]
default = ["core"]

[dependencies]
actix-web = { version = "4.5", features = ["rustls"]}
env_logger = "0.11"
log = "0.4.21"
serde = "1.0.197"
serde_json = "1.0.114"
surrealdb = {version = "1.3.1", features = ["kv-mem","kv-speedb"]}
tmflib = { git = "https://github.com/rruckley/tmflib.git"}


[features]
default = ["v4"]
v4 = []
v5 = []