[package]
name = "platypus"
version = "0.1.7"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com>"]
description = "API layer on top of TMF620 to provide product composition"
repository = "https://github.com/rruckley/platypus"
keywords = ["tmf"]

[features]
core = []
composable = ["core"]
tmf620_v4 = []
tmf622_v4 = []
tmf629_v4 = []

tmf632_v4 = []
tmf632_v5 = []

tmf620_v5 = []
tmf622_v5 = []

tmf648_v4 = []
tmf674_v4 = []
tmf674_v5 = []
v4 = ["tmf620_v4","tmf622_v4","tmf629_v4","tmf632_v4","tmf648_v4","tmf674_v4"]
v5 = ["tmf620_v5","tmf622_v5","tmf632_v5","tmf674_v5"]
metrics = ["actix-web-prometheus"]
default = ["core","v4","metrics"]

[dependencies]
actix-web = { version = "4.6.0", features = ["rustls"]}
actix-web-prometheus = { version = "0.1.2", optional = true }
env_logger = "0.11"
etag = "4.0.0"
log = "0.4.21"
serde = "1.0.197"
serde_json = "1.0.114"
surrealdb = {version = "1.3.1"}
tmflib = "0.1.17"


