[package]
name = "platypus"
version = "0.1.7"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com>"]
description = "API layer on top of TMF620 to provide product composition"
repository = "https://github.com/rruckley/platypus"
keywords = ["tmf"]

[features]
core = []
composable = ["core"]
tmf620_v4 = []
tmf622_v4 = []
tmf629_v4 = []

tmf632_v4 = []
tmf632_v5 = []

tmf620_v5 = []
tmf622_v5 = []

tmf648_v4 = []
tmf674_v4 = []
tmf674_v5 = []
v4 = ["tmf620_v4","tmf622_v4","tmf629_v4","tmf632_v4","tmf648_v4","tmf674_v4","tmflib/build-V4"]
v5 = ["tmf620_v5","tmf622_v5","tmf632_v5","tmf674_v5","tmflib/build-V5"]
default = ["core","v4"]

[dependencies]
actix-web = { version = "4.9.0", features = ["rustls"]}
env_logger = "0.11.6"
etag = "4.0.0"
log = "0.4.22"
serde = "1.0.217"
serde_json = "1.0.125"
surrealdb = {version = "2.1.4"}
tmflib = "0.1.23"


