[package]
name = "platypus"
version = "0.1.7"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com>"]
description = "TMF ODA Component Platform"
repository = "https://github.com/rruckley/platypus"
keywords = ["tmf"]

[features]
core = ["TMFC001_v4"]
composable = ["core"]
tmf620_v4 = []
tmf622_v4 = []
tmf629_v4 = []

tmf632_v4 = []
tmf632_v5 = []

tmf620_v5 = []
tmf622_v5 = []

tmf648_v4 = []
tmf674_v4 = []
tmf674_v5 = []

tmf688_v4 = []

# ODA Features V4
TMFC001_v4 = ["tmf620_v4","tmflib/tmf620","tmflib/build-V4"]
TMFC002_v4 = ["tmf622_v4","tmflib/tmf622","tmf648_v4","tmflib/build-V4"]
TMFC028_v4 = ["tmf632_v4","tmflib/tmf632","tmflib/build-V4"]

# ODA Features V5
TMFC001_v5 = ["tmf620_v5","tmflib/tmf620","tmflib/build-V5"]
TMFC002_v5 = ["tmf622_v5","tmflib/tmf622","tmf648_v4","tmflib/build-V5"]

v4 = ["tmf620_v4","tmf622_v4","tmf629_v4","tmf632_v4","tmf648_v4","tmf674_v4","tmflib/build-V4"]
v5 = ["tmf620_v5","tmf622_v5","tmf632_v5","tmf674_v5","tmflib/build-V5"]
default = ["core"]

[dependencies]
actix-web = { version = "4.9.0", features = ["rustls"]}
env_logger = "0.11.6"
etag = "4.0.0"
log = "0.4.22"
serde = "1.0.210"
serde_json = "1.0.135"
surrealdb = {version = "2.1.4"}
tmflib = "0.1.24"


